### ISSUE TITLE
오픈소스 사용 논의

### ISSUE THREAD

**Issue by Parkhyunseo** [Parkhyunseo/D2-FEST-mini-KOK#10]
1. React Native 로그인 연동 오픈소스 사용
[https://github.com/react-native-seoul/react-native-naver-login](url)
개발 비용 검토, 현재 개발 진행률 측정 후 사용을 고려합시다.

**Comment by GiPyoo** [comment]
사용해야 할것 같습니다.

**Comment by Parkhyunseo** [comment]
그렇다면 오픈소스 사용 후 필요한 내용은 추가 개발하는 식으로 가겠습니다.
