### ISSUE TITLE
할 일

### ISSUE THREAD

**Issue by GiPyoo** [Parkhyunseo/D2-FEST-mini-KOK#13]
- [ ] 네이버 로그인 
- [ ] map에 pin 찍기
    - [ ] 이미지 메타데이터 활용
- [ ] 글 장성시 db 저장 ( 핀위치, 글 내용)
- [ ] 핀 렌더링 함수
- [ ] 이미지 파일 올리기

- google map 연동 => 모듈 사용 연결하기만 하면 됩니다. (VIEW)

**Comment by Parkhyunseo** [comment]
제가 잘게 쪼개서 Issue로 만들고 칸반보드에 올리겠습니다.

**Comment by Parkhyunseo** [comment]
이슈를 분리 및 재작성한 관계로 이슈를 Close 하겠습니다.
